Mobile version
Suzi216/Portfolio pull request #2
Opened 2022-05-30 22:04 UTC by Suzi216

Built the middle section of the mobile version.
Created the html file for Work and About me sections.
Created the css file to design the Work and About me sections.
Adding linters to check for errors.

2022-05-30 23:08 UTC, Mre55 requested changes
**Hi @Suzi216,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +        <h1 class="tonic">Tonic</h1>
For good semantic usage purposes kindly, replace this `nav` tag with another tag like `div` or `article` we only use the `nav` tag inside the `header` tag. Also, change the `h1` text with `hx` tag we only use `h1` for our website title and you have it above. So replace all `h1`s below with the tag `h2-h6`.

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +      </section>
Please wrap these cards inside one big `section` and that section should have `background-color: #E5E5E5` so that you can give `background-color: #fff` for your cards to match the Figma design. Also, add more cards as you only have two.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="340" alt="image" src="https://user-images.githubusercontent.com/34578631/171065505-5cc4082e-10f4-4f26-895e-d2fd4100673e.png"> | <img width="370" alt="image" src="https://user-images.githubusercontent.com/34578631/171065525-45e0da7b-cb8c-45ea-9664-d36feb27dab0.png"> |

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +      </section>
Please stick to the Figma design as much as possible and your cards give a `border` and `border-radius` to match the design. Also, your cards are more left make sure they are centered.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="340" alt="image" src="https://user-images.githubusercontent.com/34578631/171065505-5cc4082e-10f4-4f26-895e-d2fd4100673e.png"> | <img width="370" alt="image" src="https://user-images.githubusercontent.com/34578631/171065525-45e0da7b-cb8c-45ea-9664-d36feb27dab0.png"> |

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +          <button type="button" name="button" class="Job1-button"> See Project</button>
Also, please follow the button style of the design for `See Project` button. Center the text and implement the hover action styling too.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="117" alt="image" src="https://user-images.githubusercontent.com/34578631/171065850-b0275f72-5f45-4290-8e2a-67821e2e67d8.png"> | <img width="141" alt="image" src="https://user-images.githubusercontent.com/34578631/171065866-3e91951e-35d0-4bd2-84e7-2dae0d643851.png"> |

Also, implement the same things for `Get my resume` button below in the `About` section.

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +        <h1 class="head">About <br> Myself </h1>
Kindly, replace this `h1` with another tag as stated above.

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +        <p class="pr">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need c
Your `About` section is more to the left kindly, edit that to match the design and give some padding-left. And remove the background image as we don't have it for the `About` section. Rather we have `border-top-right-radius` for the white background.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="405" alt="image" src="https://user-images.githubusercontent.com/34578631/171066142-5263eeb9-f742-4575-95e4-cdeccda69a70.png"> | <img width="374" alt="image" src="https://user-images.githubusercontent.com/34578631/171066222-3c4d7076-1880-4748-85be-32679e0d1062.png"> |

And give spacing between the `social-media` icons. And implement the button styling as suggested above for the `Get my resume` button.

2022-05-30 23:08 UTC, Mre55 commented on index.html
> +          <img src="images/Union1.png" alt="">
Please use `ul` and `li` for `Languages`, `Frameworks`, and `Skills` as stated in the project requirement.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/34578631/171066532-455915f1-7647-4311-ba4f-edf61625c6e2.png">

And change the text font and center the section to match the Figma design.

| Your Design | Figma Design |
|-------------|---------------|
| <img width="408" alt="image" src="https://user-images.githubusercontent.com/34578631/171066680-aaa6ce3b-bd91-443a-93fc-526c2db8041d.png"> | <img width="373" alt="image" src="https://user-images.githubusercontent.com/34578631/171066690-6d7877aa-3629-4977-bd59-9c47e88177fc.png"> |

2022-06-01 10:39 UTC, arslanbisharat approved these changes
Hi,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 10:45 UTC, merged

2022-06-30 08:20 UTC, Nemwel-Boniface reviewed
## Hello @Suzi216    :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes that were requested by the previous reviewer.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 
## [Optional] suggestions

- [OPTIONAL] - Kindly make sure to include an MIT.md in your project. If you may be in doubt, have a look at [this](https://github.com/microverseinc/readme-template/blob/master/MIT.md) example MIT.md this way your documentation will be 100% complete :sunglasses: .

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._